### ISSUE TITLE
 Issue with the MCX gate using CFLOBDD backend

### ISSUE THREAD

**Issue by s-jobra** [trishullab/Quasimodo#9]
Hi,
I just wanted to let you know that it looks like there is some issue with CFLOBDDs and the MCX gate as well, specifically when i run this
```
#include "quantum_circuit.h"

int main()
{
    CFLOBDDQuantumCircuit qc;
    qc.setNumQubits(3);
    std::vector<long int> controllers = {0, 2};
    qc.ApplyMCXGate(controllers, 1);

}
```
it crashes with
```
Hash of a non-canonical ReturnMapHandle occurred
Aborted
```

**Comment by cs14b052** [comment]
Looks like it was an older version. Please check now.

**Comment by s-jobra** [comment]
Hmm I still get the same error for the above mentioned example.

**Comment by cs14b052** [comment]
Fixed it. The issue was that the current code has been written with the assumption of the index of controllers < controlled. I fixed it now. However, there may be other gates like this. I will try and fix them one-by-one.

**Comment by s-jobra** [comment]
Thank you very much!
